# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SpherizedURDFGenerator::STG SpherizedURDFGenerator::SFWhite SpherizedURDFGenerator::API SpherizedURDFGenerator::Base SpherizedURDFGenerator::MVBB SpherizedURDFGenerator::qHull SpherizedURDFGenerator::BBox SpherizedURDFGenerator::Exceptions SpherizedURDFGenerator::pcube SpherizedURDFGenerator::Geometry SpherizedURDFGenerator::Matrix SpherizedURDFGenerator::MedialAxis SpherizedURDFGenerator::MinMax SpherizedURDFGenerator::SphereTree SpherizedURDFGenerator::Storage SpherizedURDFGenerator::Surface SpherizedURDFGenerator::Export SpherizedURDFGenerator::ManifoldPlus SpherizedURDFGenerator::sphereTreeWrapper SpherizedURDFGenerator::SpherizedURDFGenerator SpherizedURDFGenerator::convex SpherizedURDFGenerator::spherized)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target SpherizedURDFGenerator::STG
add_library(SpherizedURDFGenerator::STG STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::STG PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-Wall;-Wextra;-Wshadow;-Wnon-virtual-dtor;-Wold-style-cast;-Wcast-align;-Wunused;-Woverloaded-virtual;-Wpedantic;-Wconversion;-Wsign-conversion;-Wnull-dereference;-Wdouble-promotion;-Wformat=2;-Wimplicit-fallthrough;-Wmisleading-indentation;-Wduplicated-cond;-Wduplicated-branches;-Wlogical-op;-Wuseless-cast;-Wsuggest-override>;\$<\$<COMPILE_LANGUAGE:C>:-Wall;-Wextra;-Wshadow;-Wnon-virtual-dtor;-Wold-style-cast;-Wcast-align;-Wunused;-Woverloaded-virtual;-Wpedantic;-Wconversion;-Wsign-conversion;-Wnull-dereference;-Wdouble-promotion;-Wformat=2;-Wimplicit-fallthrough;-Wmisleading-indentation;-Wduplicated-cond;-Wduplicated-branches;-Wlogical-op;-Wuseless-cast;-Wsuggest-override>;\$<\$<COMPILE_LANGUAGE:CUDA>:-Wall;-Wextra;-Wunused;-Wconversion;-Wshadow>"
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::SFWhite;SpherizedURDFGenerator::API;SpherizedURDFGenerator::Base;SpherizedURDFGenerator::MVBB;SpherizedURDFGenerator::qHull;SpherizedURDFGenerator::BBox;SpherizedURDFGenerator::Exceptions;SpherizedURDFGenerator::pcube;SpherizedURDFGenerator::Geometry;SpherizedURDFGenerator::Matrix;SpherizedURDFGenerator::MedialAxis;SpherizedURDFGenerator::MinMax;SpherizedURDFGenerator::SphereTree;SpherizedURDFGenerator::Storage;SpherizedURDFGenerator::Surface;SpherizedURDFGenerator::Export"
)

# Create imported target SpherizedURDFGenerator::SFWhite
add_library(SpherizedURDFGenerator::SFWhite STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::API
add_library(SpherizedURDFGenerator::API STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::API PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::SFWhite"
)

# Create imported target SpherizedURDFGenerator::Base
add_library(SpherizedURDFGenerator::Base STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::MVBB
add_library(SpherizedURDFGenerator::MVBB STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::qHull
add_library(SpherizedURDFGenerator::qHull STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::BBox
add_library(SpherizedURDFGenerator::BBox STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::BBox PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::qHull;SpherizedURDFGenerator::MVBB"
)

# Create imported target SpherizedURDFGenerator::Exceptions
add_library(SpherizedURDFGenerator::Exceptions STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::pcube
add_library(SpherizedURDFGenerator::pcube STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::Geometry
add_library(SpherizedURDFGenerator::Geometry STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::Geometry PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::pcube;SpherizedURDFGenerator::Matrix"
)

# Create imported target SpherizedURDFGenerator::Matrix
add_library(SpherizedURDFGenerator::Matrix STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::MedialAxis
add_library(SpherizedURDFGenerator::MedialAxis STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::MinMax
add_library(SpherizedURDFGenerator::MinMax STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::SphereTree
add_library(SpherizedURDFGenerator::SphereTree STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::SphereTree PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::Geometry;SpherizedURDFGenerator::Storage"
)

# Create imported target SpherizedURDFGenerator::Storage
add_library(SpherizedURDFGenerator::Storage STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::Surface
add_library(SpherizedURDFGenerator::Surface STATIC IMPORTED)

set_target_properties(SpherizedURDFGenerator::Surface PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::Geometry;SpherizedURDFGenerator::Storage;SpherizedURDFGenerator::Base"
)

# Create imported target SpherizedURDFGenerator::Export
add_library(SpherizedURDFGenerator::Export STATIC IMPORTED)

# Create imported target SpherizedURDFGenerator::ManifoldPlus
add_library(SpherizedURDFGenerator::ManifoldPlus SHARED IMPORTED)

# Create imported target SpherizedURDFGenerator::sphereTreeWrapper
add_library(SpherizedURDFGenerator::sphereTreeWrapper SHARED IMPORTED)

set_target_properties(SpherizedURDFGenerator::sphereTreeWrapper PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::STG;yaml-cpp;irmv_core::irmv_core"
)

# Create imported target SpherizedURDFGenerator::SpherizedURDFGenerator
add_library(SpherizedURDFGenerator::SpherizedURDFGenerator SHARED IMPORTED)

set_target_properties(SpherizedURDFGenerator::SpherizedURDFGenerator PROPERTIES
  INTERFACE_LINK_LIBRARIES "SpherizedURDFGenerator::STG;SpherizedURDFGenerator::SFWhite;SpherizedURDFGenerator::API;SpherizedURDFGenerator::Base;SpherizedURDFGenerator::MVBB;SpherizedURDFGenerator::qHull;SpherizedURDFGenerator::BBox;SpherizedURDFGenerator::Exceptions;SpherizedURDFGenerator::pcube;SpherizedURDFGenerator::Geometry;SpherizedURDFGenerator::Matrix;SpherizedURDFGenerator::MedialAxis;SpherizedURDFGenerator::MinMax;SpherizedURDFGenerator::SphereTree;SpherizedURDFGenerator::Storage;SpherizedURDFGenerator::Surface;SpherizedURDFGenerator::Export;SpherizedURDFGenerator::ManifoldPlus;SpherizedURDFGenerator::sphereTreeWrapper;irmv_core::irmv_core;gmp;tinyxml2;urdfdom_model;urdfdom_world;urdfdom_sensor"
)

# Create imported target SpherizedURDFGenerator::convex
add_executable(SpherizedURDFGenerator::convex IMPORTED)

# Create imported target SpherizedURDFGenerator::spherized
add_executable(SpherizedURDFGenerator::spherized IMPORTED)

# Import target "SpherizedURDFGenerator::STG" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::STG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::STG PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/libSTG.a"
  )

# Import target "SpherizedURDFGenerator::SFWhite" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::SFWhite APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::SFWhite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/API/SFWhite/libSFWhite.a"
  )

# Import target "SpherizedURDFGenerator::API" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::API APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::API PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/API/libAPI.a"
  )

# Import target "SpherizedURDFGenerator::Base" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Base APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Base PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Base/libBase.a"
  )

# Import target "SpherizedURDFGenerator::MVBB" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::MVBB APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::MVBB PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/BBox/MVBB/libMVBB.a"
  )

# Import target "SpherizedURDFGenerator::qHull" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::qHull APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::qHull PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/BBox/qHull/libqHull.a"
  )

# Import target "SpherizedURDFGenerator::BBox" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::BBox APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::BBox PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/BBox/libBBox.a"
  )

# Import target "SpherizedURDFGenerator::Exceptions" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Exceptions APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Exceptions PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Exceptions/libExceptions.a"
  )

# Import target "SpherizedURDFGenerator::pcube" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::pcube APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::pcube PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Geometry/pcube/libpcube.a"
  )

# Import target "SpherizedURDFGenerator::Geometry" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Geometry PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Geometry/libGeometry.a"
  )

# Import target "SpherizedURDFGenerator::Matrix" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Matrix APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Matrix PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/LinearAlgebra/libMatrix.a"
  )

# Import target "SpherizedURDFGenerator::MedialAxis" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::MedialAxis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::MedialAxis PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/MedialAxis/libMedialAxis.a"
  )

# Import target "SpherizedURDFGenerator::MinMax" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::MinMax APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::MinMax PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/MinMax/libMinMax.a"
  )

# Import target "SpherizedURDFGenerator::SphereTree" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::SphereTree APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::SphereTree PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/SphereTree/libSphereTree.a"
  )

# Import target "SpherizedURDFGenerator::Storage" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Storage/libStorage.a"
  )

# Import target "SpherizedURDFGenerator::Surface" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Surface APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Surface PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Surface/libSurface.a"
  )

# Import target "SpherizedURDFGenerator::Export" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::Export APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::Export PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/sphere_tree/src/Export/libExport.a"
  )

# Import target "SpherizedURDFGenerator::ManifoldPlus" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::ManifoldPlus APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::ManifoldPlus PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/third_party/ManifoldPlus/libManifoldPlus.so.1.4"
  IMPORTED_SONAME_RELEASE "libManifoldPlus.so.1"
  )

# Import target "SpherizedURDFGenerator::sphereTreeWrapper" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::sphereTreeWrapper APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::sphereTreeWrapper PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/bot_utils/sphereTreeWrapper/libsphereTreeWrapper.so.1.4"
  IMPORTED_SONAME_RELEASE "libsphereTreeWrapper.so.1"
  )

# Import target "SpherizedURDFGenerator::SpherizedURDFGenerator" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::SpherizedURDFGenerator APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::SpherizedURDFGenerator PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/libSpherizedURDFGenerator.so"
  IMPORTED_SONAME_RELEASE "libSpherizedURDFGenerator.so"
  )

# Import target "SpherizedURDFGenerator::convex" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::convex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::convex PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/app/convex"
  )

# Import target "SpherizedURDFGenerator::spherized" for configuration "Release"
set_property(TARGET SpherizedURDFGenerator::spherized APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SpherizedURDFGenerator::spherized PROPERTIES
  IMPORTED_LOCATION_RELEASE "/workspace/build_dkr/app/spherized"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
