# Default sphere-tree preset.
SingleSphere: false
Method: 2
Grid:
  TesterLevers: -1
  Branch: 8
  Depth: 1
  NumCoverPts: 10000
  MinCoverPts: 5
  Verify: false
  Nopause: false
  Eval: false
Medial:
  TesterLevers: -1
  Branch: 8
  Depth: 1
  NumCoverPts: 20000
  MinCoverPts: 5
  InitSpheres: 1000
  ErFact: 2
  SpheresPerNode: 1000
  Verify: false
  Nopause: true
  Eval: false
  UseMerge: true
  UseBurst: false
  UseExpand: false
  Optimise: 1
  BalExcess: 0.0
  MaxOptLevel: 1
Spawn:
  TesterLevers: -1
  Branch: 8
  Depth: 1
  NumCoverPts: 5000
  MinCoverPts: 5
  Verify: false
  Nopause: false
  Eval: false
Octree:
  Depth: 1
  Verify: false
  Nopause: false
  Eval: false
SimplifyRatio: 0.02
